version: '3'

services:
  next-app:
    container_name: lietuviai-at-nextjs13
    build:
      context: .
      dockerfile: Dockerfile
      args:
        WORDPRESS_API_URL: ${WORDPRESS_API_URL}
        NEXT_PUBLIC_DOMAIN: ${NEXT_PUBLIC_DOMAIN}
        NEXT_PUBLIC_GA_ID: ${NEXT_PUBLIC_GA_ID}
    restart: always
    ports:
      - 3000:3000
    networks:
      - lietuviai_network

  # Add more containers below (nginx, postgres, etc.)

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  lietuviai_network:
    external: true


# Source
# https://github.com/vercel/next.js/blob/canary/examples/with-docker-compose/README.md