import Link from "next/link"
import Script from "next/script"
import Ga from "./ga"

import "./globals.css"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-[#1e2227] p-8 text-white">
        <nav>
          <ul>
            <li>
              <Link href="/page-1">Page-1</Link>
            </li>
            <li>
              <Link href="/page-2">Page-2</Link>
            </li>
          </ul>
        </nav>
        {children}

        <Ga />
      </body>
    </html>
  )
}
